-- Scripts criado para o projeto --
CREATE TABLE USUARIO (
	EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
 	PRIMARY KEY (EMAIL) 
);
CREATE TABLE FUNCIONARIO (
	CPF INT NOT NULL,
	NOME VARCHAR(100) NOT NULL,
    SENHA VARCHAR(100)NOT NULL,
    TELEFONE_ID INT NOT NULL,
    ENDERECO_ID INT NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
  PRIMARY KEY (CPF) 
);
CREATE TABLE ENDERECO (
	ID INT NOT NULL,
	RUA VARCHAR(100) NOT NULL,
    NUMERO_END VARCHAR(100) NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    CEP VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(100) NOT NULL,
    CPF_END INT NOT NULL,
  PRIMARY KEY (ID) 
);
CREATE TABLE TELEFONE (
	ID INT NOT NULL,
	DDD INT NOT NULL,
    NUMERO_TEL INT NOT NULL,
    CPF_TEL INT NOT NULL,
  PRIMARY KEY (ID) 
);

ALTER TABLE FUNCIONARIO
ADD FOREIGN KEY (TELEFONE_ID)
REFERENCES TELEFONE(ID);

ALTER TABLE FUNCIONARIO
ADD FOREIGN KEY (ENDERECO_ID)
REFERENCES ENDERECO(ID);

ALTER TABLE TELEFONE
ADD FOREIGN KEY (CPF_TEL)
REFERENCES FUNCIONARIO(CPF);

ALTER TABLE ENDERECO
ADD FOREIGN KEY (CPF_END)
REFERENCES FUNCIONARIO(CPF);

CREATE SEQUENCE S_ENDERECO 
	MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 ;

CREATE SEQUENCE S_TELEFONE 
	MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 ;
